events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Прокси для User Service
        location /users/ {
            proxy_pass http://host.docker.internal:8081/profile;
        }

        # Прокси для Booking Service
        location /bookings/ {
            proxy_pass http://host.docker.internal:8082/book;
        }
    }
}