events {} #обязательный блок (он необходим чтобы nginx работал)

http {
    server {
        listen 80; #Когда придет запрос nginx будет обрабатывать запрос в этом порту

        location /api/users/ {
            proxy_pass http://userService:8080/; #цифры это порт который слушает мое приложение, также указываем имя контейнера(userService)
        }

        location /api/bookings/ {
            proxy_pass http://bookingService:8081/;
        }
    }
}