worker_processes  1;

events {
    worker_connections  1024;
}

http {
    server {
        listen 8443 ssl;
        server_name localhost;

        ssl_certificate     "D:/DistributedMicroservice/certs/server.crt";
        ssl_certificate_key "D:/DistributedMicroservice/certs/server.key";
        ssl_client_certificate "D:/DistributedMicroservice/certs/ca.crt";
        ssl_verify_client optional;

        location / {
            proxy_pass http://localhost:8080;
        }
    }
}