apiVersion: v1
kind: Service
metadata:
  name: listing-service
spec:
  selector:
    app: listing-service
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.listingService.grpcPort }}
      targetPort: grpc
    - name: health
      protocol: TCP
      port: {{ .Values.listingService.healthPort }}
      targetPort: health