// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/listing.proto

package listing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingRequest) Reset() {
	*x = ListingRequest{}
	mi := &file_proto_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingRequest) ProtoMessage() {}

func (x *ListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingRequest.ProtoReflect.Descriptor instead.
func (*ListingRequest) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{0}
}

func (x *ListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,3,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingResponse) Reset() {
	*x = ListingResponse{}
	mi := &file_proto_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingResponse) ProtoMessage() {}

func (x *ListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingResponse.ProtoReflect.Descriptor instead.
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{1}
}

func (x *ListingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_proto_listing_proto protoreflect.FileDescriptor

const file_proto_listing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/listing.proto\x12\alisting\" \n" +
	"\x0eListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x0fListingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12!\n" +
	"\fis_available\x18\x03 \x01(\bR\visAvailable2U\n" +
	"\x0elistingService\x12C\n" +
	"\x0eGetListingInfo\x12\x17.listing.ListingRequest\x1a\x18.listing.ListingResponseB\vZ\t./listingb\x06proto3"

var (
	file_proto_listing_proto_rawDescOnce sync.Once
	file_proto_listing_proto_rawDescData []byte
)

func file_proto_listing_proto_rawDescGZIP() []byte {
	file_proto_listing_proto_rawDescOnce.Do(func() {
		file_proto_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_listing_proto_rawDesc), len(file_proto_listing_proto_rawDesc)))
	})
	return file_proto_listing_proto_rawDescData
}

var file_proto_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_listing_proto_goTypes = []any{
	(*ListingRequest)(nil),  // 0: listing.ListingRequest
	(*ListingResponse)(nil), // 1: listing.ListingResponse
}
var file_proto_listing_proto_depIdxs = []int32{
	0, // 0: listing.listingService.GetListingInfo:input_type -> listing.ListingRequest
	1, // 1: listing.listingService.GetListingInfo:output_type -> listing.ListingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_listing_proto_init() }
func file_proto_listing_proto_init() {
	if File_proto_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_listing_proto_rawDesc), len(file_proto_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_listing_proto_goTypes,
		DependencyIndexes: file_proto_listing_proto_depIdxs,
		MessageInfos:      file_proto_listing_proto_msgTypes,
	}.Build()
	File_proto_listing_proto = out.File
	file_proto_listing_proto_goTypes = nil
	file_proto_listing_proto_depIdxs = nil
}
